filter:
    excluded_paths:
        - 'tests/*'
        - 'src/Database/*'

checks:
    php:
      code_rating: true
      duplication: true
      optional_parameters_at_the_end: true
      parameters_in_camelcaps: true
      properties_in_camelcaps: true
      fix_use_statements:
          remove_unused: true
          preserve_multiple: false
          preserve_blanklines: false
          order_alphabetically: true
      classes_in_camel_caps: true

coding_style:
    php: {  }
